################################################################################
#                                                                              #
#                   Configuração principal do plugin ARENA                     #
#                                                                              #
################################################################################

# Configurações do MySQL para conexão ao banco de dados
mysql:
  enable: false             # Define se o MySQL está habilitado (true = ativo / false = desativa e impede o plugin de funcionar)
  host: localhost           # Endereço do servidor MySQL
  port: 3306                # Porta do MySQL (padrão 3306)
  database: arena           # Nome do banco de dados
  user: root                # Usuário do banco de dados
  password: ''              # Senha do banco (deixe vazio se não tiver)

# Itens de proteção na arena
protection-items:
  name: "&e&lARENA"        # Nome exibido para os itens protegidos da arena.
                           # Pode conter códigos de cores Minecraft (exemplo: "§6ARENA").
                           #
                           # Essa marca serve para identificar os itens do kit da arena,
                           # protegendo-os contra uso fora da arena.
                           #
                           # Funcionamento:
                           # - Os itens do kit ganham esse nome personalizado.
                           # - Jogadores só podem sair da arena com itens que possuam essa marca.
                           # - Itens sem essa marca, se detectados no inventário fora da arena,
                           #   serão automaticamente removidos para evitar exploits e bugs.
                           #
                           # Objetivo:
                           # - Impedir que jogadores buguem ou abusem ficando com itens do kit fora da arena.
                           # - Garantir que os itens da arena sejam exclusivos e controlados.
                           #
                           # Para personalizar a cor e estilo, use códigos de cor do Minecraft, por exemplo:
                           # "§6ARENA" (dourado), "§cARENA" (vermelho), "§bARENA" (azul claro), etc.

# Configurações diversas
configuracoes:
  tempo_espera_kill_millis: 180000  # Tempo de espera entre kills para contagem (milissegundos).
                                    # Exemplo: 180000 = 3 minutos.

# Mensagens customizadas (com códigos de cor Minecraft §)
mensagens:

  # Kills e restrições de IP
  ip_invalido: "§6§lARENA §cIP inválido, kill não foi contada."
  mesmo_ip: "§6§lARENA §cVocê não pode ganhar kills de jogadores com mesmo IP."
  kill_valida: "§a§l+1 kill §7(kit restaurado)"
  kill_invalida: "§6§lARENA §eVocê já matou esse jogador recentemente. Kill não foi contada."

  # Morte e saída da arena
  morreu_na_arena: "§6§lARENA §cVocê morreu na arena, seus itens foram limpos."
  morte_jogador: "§6§lARENA §cVocê morreu na arena!"
  nao_esta_na_arena: "§6§lARENA §cVocê não está na arena!"
  ja_na_arena: "§6§lARENA §cVocê já está na arena!"
  inventario_nao_vazio: "§6§lARENA §cVocê só pode entrar na arena com inventário vazio!"
  localizacao_nao_configurada: "§6§lARENA §cLocalização da arena não configurada! Contate um administrador."

  # Camarote
  camarote_removido_sair: "§6§lARENA §cVocê foi removido do camarote ao sair do servidor."
  camarote_removido_trocar_mundo: "§6§lARENA §cVocê foi removido do camarote ao trocar de mundo."
  modo_survival_entrada: "§6§lARENA §cVocê entrou e foi colocado no modo survival."
  modo_survival_camarote_reconectar: "§6§lARENA §cVocê foi colocado em modo survival após reconectar ao camarote."
  modo_survival_forcado: "§6§lARENA §cVocê foi colocado no modo survival após {motivo}."
  camarote_teleportado_de_volta: "§6§lARENA §cVocê foi teleportado de volta ao camarote, pois ultrapassou a distância de 100 blocos."
  camarote_drop_bloqueado: "§6§lARENA §cVocê não pode dropar itens enquanto estiver no camarote."
  espectador_drop_bloqueado: "§6§lARENA §cVocê não pode dropar itens enquanto estiver em modo espectador."
  camarote_pickup_bloqueado: "§6§lARENA §cVocê não pode pegar itens enquanto estiver no camarote."

  # Permissões e uso
  sem_permissao: "§6§lARENA §cVocê não tem permissão para usar este comando."
  setou_entrada: "§a✔ Você setou a entrada da Arena!"
  setou_saida: "§a✔ Você setou a saída da Arena!"
  kit_existente: "§eJá existe um kit salvo. Use §a/arena limparkit §eantes de salvar um novo kit."
  kit_limpo: "§a✔ Kit da arena removido com sucesso do itens.yml!"
  reload_sucesso: "§a✔ Configuração da Arena recarregada com sucesso!"
  lista_camarote_sucesso: "§a✔ Todos os jogadores no camarote foram listados no console."
  setou_camarote: "§a✔ Você setou a localização do camarote!"
  nao_esta_na_arena: "§6§lARENA §cApenas jogadores podem usar este comando."
  ja_na_arena: "§6§lARENA §cVocê já está na arena!"

  # Itens protegidos fora da arena
  item_protegido_drop_fora: "§6§lARENA §cVocê não pode dropar itens protegidos fora da arena."
  item_protegido_equipar_fora: "§6§lARENA §cVocê não pode equipar itens protegidos fora da arena."
  item_protegido_manipular_fora: "§6§lARENA §cVocê não pode manipular itens protegidos fora da arena."
  item_protegido_arrastar_fora: "§6§lARENA §cVocê não pode arrastar itens protegidos fora da arena."
  item_protegido_trocar_maos_fora: "§6§lARENA §cVocê não pode trocar itens protegidos de mão fora da arena."
  item_protegido_pegar_fora: "§6§lARENA §cVocê não pode pegar itens protegidos fora da arena."
  item_protegido_usar_fora: "§6§lARENA §cVocê não pode usar itens protegidos fora da arena."

  # Saída da arena
  saida_contagem_ja_ativa: "§6§lARENA §cVocê já está saindo da arena!"
  saida_contagem_iniciada: "§6§lARENA §eSaída da arena iniciada. Aguarde {segundos} segundos e não tome dano para não cancelar!"
  saiu_da_arena: "§a✔ Você saiu da Arena!"
  saida_titulo: "§6Saindo da Arena..."
  saida_subtitulo: "§e{segundos} segundo(s) restantes"
  saida_cancelada_dano_recebido: "§6§lARENA §cSaída da arena cancelada porque você tomou dano!"
  saida_cancelada_dano_causado: "§6§lARENA §cSaída da arena cancelada porque você causou dano!"

  # Restrições gerais na arena
  teleporte_bloqueado: "§6§lARENA §cVocê não pode teleportar na arena!"
  drop_bloqueado: "§6§lARENA §cVocê não pode dropar itens na arena"
  comando_bloqueado: "§6§lARENA §c§l✖ §fComando bloqueado durante a partida!"

  # Bônus pós kill (vida completa, efeitos)
  bonus_pos_kill_titulo: "§6➤ Bônus de Vida Completa por kill!"
  bonus_pos_kill_subtitulo: "§7Recuperando ❤ e efeitos..."
  bonus_pos_kill_rodape: "§f❤ HP 100% ▎ Saturação 100% ▎ Efeitos Renovados!"

  # Mensagens e sons de entrada na arena
  entrada_titulo: "§6⚔ Arena ⚔"
  entrada_subtitulo: "§7Prepare-se para a batalha!"
  entrada_chat_linha1: "§6§l➤ §eBem-vindo à §6Arena§e, §f{player}§e!"
  entrada_chat_linha2: "§7Use seu talento para se destacar e §cmostrar quem manda!"
  broadcast_entrada: "§6§l[Arena] §fO jogador §e{player} §fentrou na arena! Prepare-se para a batalha!"
  som_entrada: "ENTITY_WITHER_SPAWN"  # Som tocado quando o jogador entra na arena.

  # Mensagens adicionais usadas na classe ItensArena
  arena_no_camarote_entrada: "§6§lARENA §cVocê não pode entrar na arena enquanto estiver no camarote."
  kit_nao_configurado: "§6§lARENA §cKit da arena não configurado. Configure antes de entrar."
  localizacao_saida_nao_configurada: "§6§lARENA §cLocalização de saída da arena não configurada. Contate um administrador."
  nao_esta_no_camarote: "§6§lARENA §cVocê não está no camarote."
  localizacao_camarote_nao_configurada: "§6§lARENA §cLocalização do camarote não configurada. Contate um administrador."
  entrou_no_camarote: "§6§lARENA §aVocê entrou no camarote."
  saiu_do_camarote: "§6§lARENA §aVocê saiu do camarote."
  arena_proibe_camarote: "§6§lARENA §cVocê não pode entrar no camarote enquanto estiver na arena."
  morto_proibe_camarote: "§6§lARENA §cJogadores mortos não podem entrar no camarote."
  ja_no_camarote: "§6§lARENA §cVocê já está no camarote."
  kit_salvo_sucesso: "§a✔ Kit da arena salvo com sucesso!"
  kit_aplicado_sucesso: "§a✔ Kit aplicado com sucesso!"
  kit_nao_salvo: "§6§lARENA §cNenhum kit salvo na configuração."
  erro_ao_carregar_kit: "§6§lARENA §cErro ao carregar o kit da arena."
  erro_ao_carregar_item_offhand: "§6§lARENA §cErro ao carregar item da mão secundária."
  
# Comandos liberados durante a partida (podem ser usados sem restrição)
comandos_liberados:
  - "/arena sair"
  - "/arena lista"
  - "/tell"
  - "/r"
  - "/ping"
  - "/report"
  - "/g"
  - "/."
